eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override.system-properties: false #make sure we don't override any properties for files that will inherit from this

management:
  tracing:
    sampling:
      # from 0 to 1.0 that a trace will be sampled
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http:// localhost:9411/api/v2/spans #if you want to change zipkin port