spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092 # where kafka server is running
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #serializers can be custom
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer #serializers can be custom
      properties:
        spring.json.type.mapping: paymentConfirmation:com.ecommerce.payment.kafka.PaymentNotificationRequest
server:
  port: 8060

application:
  config:
    product-url: http://localhost:8222/api/v1/product